version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/interface"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/buidler"
    schedule:
      interval: "weekly"