/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction
} from "ethers";
import {
  Contract,
  ContractTransaction,
  CallOverrides
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface CTokenPriceOracleInterface extends ethers.utils.Interface {
  functions: {
    "getPrice(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getPrice", values: [string]): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;

  events: {};
}

export class CTokenPriceOracle extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: CTokenPriceOracleInterface;

  functions: {
    getPrice(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;

    "getPrice(address)"(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: BigNumber;
    }>;
  };

  getPrice(
    cTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getPrice(address)"(
    cTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getPrice(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrice(address)"(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getPrice(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPrice(address)"(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPrice(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPrice(address)"(
      cTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
